# Generated by Django 4.2.21 on 2025-07-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
