# Generated by Django 4.2.21 on 2025-07-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('CUSTOMER', '고객'), ('EXPERT', '전문가'), ('ADMIN', '관리자')], default='CUSTOMER', max_length=10),
        ),
    ]
